branch-defaults:
  master:
    environment: null
    group_suffix: null
global:
  application_name: ehealth_task2
  branch: master
  default_ec2_keyname: null
  default_platform: Docker 1.12.6
  default_region: eu-west-1
  profile: eb-cli
  repository: ehealth_task
  sc: git
